services:
  tastyigniter-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tastyigniter:local
    hostname: tasty
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    environment:
      - APP_URL=${APP_URL:-http://localhost}
      - DOMAIN=${DOMAIN:-localhost}
      - EMAIL=${EMAIL:-admin@localhost}
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - DB_CONNECTION=mysql
      - DB_HOST=tastyigniter-database
      - DB_PORT=3306
      - DB_DATABASE=tastyigniter
      - DB_USERNAME=tastyigniter
      - DB_PASSWORD=tastyigniter
      - CACHE_DRIVER=redis
      - REDIS_HOST=tastyigniter-redis
    depends_on:
      - tastyigniter-database
      - tastyigniter-redis
    restart: always  
  tastyigniter-database:
    image: mariadb:10.7
    volumes:
      - tastyigniter-database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tastyigniter
      - MYSQL_USER=tastyigniter
      - MYSQL_PASSWORD=tastyigniter
    restart: always
  tastyigniter-redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: always

volumes:
  tastyigniter-database:
  letsencrypt:
  certbot-webroot:
